---
title: "iteration_listcols"
author: "Jasmine Zhang"
date: "2023-10-31"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
```


### Lists
```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "Jasmine")
tibble(num = vec_numeric, char = vec_char)
```

Different stuff with different lengths

```{r}
l = list(
  vec_numeric = 1:5,
  vec_char = LETTERS,
  matrix = matrix(1:10, nrow = 5, ncol = 2),
  summary = summary(rnorm(100))
) #list just store anything we have

```

Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

### Loops

```{r}
list_norm_samples = list(
  a = rnorm(20, 1, 5),
  b = rnorm(20, 0, 7),
  c = rnorm(20, 20, 1),
  d = rnorm(20, -45, 13)
)
```

mean and sd function we wrote

```{r}
mean_and_sd = function(x){
  if(!is.numeric(x)){
    stop("Argument should be numbers")
  }else if(length(x)<2){
    stop("You need at least 2 numbers to get z scores")
  }
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  ) #return two values instead of the last line
}
```

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```

```{r}
output = vector("list", length = 4) #empty list to store the results we want

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
}

```

### Use `map`

```{r}
output = map(list_norm_samples, mean_and_sd) #easier to read
```

